image:
  file: .gitpod.Dockerfile

ports:
    - port: 3000
      onOpen: ignore

vscode:
  extensions:
    - learnpack.learnpack-vscode
    
github:
    prebuilds:
        master: true
        pullRequests: false
        addComment: false
